# FastF1 API - Exploratory Data Analysis

This notebook explores the FastF1 API to understand:
- Available data types and structures
- How to access different datasets
- What information is available for predictions

In [1]:
import fastf1
import pandas as pd
import numpy as np

# Enable cache for faster data loading
fastf1.Cache.enable_cache('f1_cache')

## 1. Session Data Overview

Let's start by loading a recent session and exploring what data is available.

In [2]:
# Load a recent session (e.g., Abu Dhabi 2024 Race)
session = fastf1.get_session(2024, 'Abu Dhabi', 'R')
session.load()

print(f"Event: {session.event['EventName']}")
print(f"Session: {session.name}")
print(f"Date: {session.event['EventDate']}")

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
_api        WARNING 	Driver  2: Car data is incomplete!
_api        WARNING 	Driver  3: Car data is incomplete!
_api        WARNING 	Driver  5: Car data is incomplete!
_api        WARNING 	Driver  6: Car data is incomplete!
_api        WARNING 	Driver  7: Car data is incomplete!
_api        WARNING 	Driver  8: Car data is incomplete!
_api        WARNING 	Driver  9: Car data is incomplete!
_api        WARNING 	Driver 12: Car data is incomplete!
_api        WARNING 	Driver 15: Car data is incomplete!
_api        WARNING 	Driver 17: Car data is incomplete!
_api        WARNING 	Driver 19: Car data is incomplete!
_api        WARNING 	Driver 21: Car data is incomplete!
_api        WARNING 	Driver 25: Car data is incomplete!
_api        WARNING 	Driver 26: Car data is incomplete!
_api        WARNING 	Driver 28: Car data is incomplete!
_api        WARNING 	Driver 29: Car data is incomplete!
_api        WARNING 	Driver 31: Car data is incomplete!
_api        WARNING 	Driver 43: Car data is incomplete!
_api        WARNING 	Driver 44: Car data is incomplete!
_api        WARNING 	Driver 55: Car data is incomplete!
_api        WARNING 	Driver 61: Car data is incomplete!
_api        WARNING 	Driver 63: Car data is incomplete!
_api        WARNING 	Driver 77: Car data is incomplete!
_api        WARNING 	Driver 81: Car data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver  2: Position data is incomplete!
_api        WARNING 	Driver  3: Position data is incomplete!
_api        WARNING 	Driver  5: Position data is incomplete!
_api        WARNING 	Driver  6: Position data is incomplete!
_api        WARNING 	Driver  7: Position data is incomplete!
_api        WARNING 	Driver  8: Position data is incomplete!
_api        WARNING 	Driver  9: Position data is incomplete!
_api        WARNING 	Driver 12: Position data is incomplete!
_api        WARNING 	Driver 15: Position data is incomplete!
_api        WARNING 	Driver 17: Position data is incomplete!
_api        WARNING 	Driver 19: Position data is incomplete!
_api        WARNING 	Driver 21: Position data is incomplete!
_api        WARNING 	Driver 25: Position data is incomplete!
_api        WARNING 	Driver 26: Position data is incomplete!
_api        WARNING 	Driver 28: Position data is incomplete!
_api        WARNING 	Driver 29: Position data is incomplete!
_api        WARNING 	Driver 30: Position data is incomplete!
_api        WARNING 	Driver 31: Position data is incomplete!
_api        WARNING 	Driver 43: Position data is incomplete!
_api        WARNING 	Driver 44: Position data is incomplete!
_api        WARNING 	Driver 55: Position data is incomplete!
_api        WARNING 	Driver 61: Position data is incomplete!
_api        WARNING 	Driver 63: Position data is incomplete!
_api        WARNING 	Driver 77: Position data is incomplete!
_api        WARNING 	Driver 81: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']

Event: Abu Dhabi Grand Prix
Session: Race
Date: 2024-12-08 00:00:00

## 2. Results Data

Race results including positions, points, and status.

In [3]:
# Get race results
results = session.results
print("Available columns in results:")
print(results.columns.tolist())
print("\nFirst few results:")
results[['DriverNumber', 'BroadcastName', 'Abbreviation', 'TeamName', 'Position', 'GridPosition', 'Points', 'Status']]

Available columns in results:
['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName', 'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName', 'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition', 'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps']

First few results:

,DriverNumber,BroadcastName,Abbreviation,TeamName,Position,GridPosition,Points,Status
4,4,L NORRIS,NOR,McLaren,1.0,1.0,25.0,Finished
55,55,C SAINZ,SAI,Ferrari,2.0,3.0,18.0,Finished
16,16,C LECLERC,LEC,Ferrari,3.0,19.0,15.0,Finished
44,44,L HAMILTON,HAM,Mercedes,4.0,16.0,12.0,Finished
63,63,G RUSSELL,RUS,Mercedes,5.0,6.0,10.0,Finished
1,1,M VERSTAPPEN,VER,Red Bull Racing,6.0,4.0,8.0,Finished
10,10,P GASLY,GAS,Alpine,7.0,5.0,6.0,Finished
27,27,N HULKENBERG,HUL,Haas F1 Team,8.0,7.0,4.0,Finished
14,14,F ALONSO,ALO,Aston Martin,9.0,8.0,2.0,Finished
81,81,O PIASTRI,PIA,McLaren,10.0,2.0,1.0,Finished
23,23,A ALBON,ALB,Williams,11.0,18.0,0.0,Lapped
22,22,Y TSUNODA,TSU,RB,12.0,11.0,0.0,Lapped
24,24,G ZHOU,ZHO,Kick Sauber,13.0,15.0,0.0,Lapped
18,18,L STROLL,STR,Aston Martin,14.0,13.0,0.0,Lapped
61,61,J DOOHAN,DOO,Alpine,15.0,17.0,0.0,Lapped
20,20,K MAGNUSSEN,MAG,Haas F1 Team,16.0,14.0,0.0,Lapped
30,30,L LAWSON,LAW,RB,17.0,12.0,0.0,Retired
77,77,V BOTTAS,BOT,Kick Sauber,18.0,9.0,0.0,Retired
43,43,F COLAPINTO,COL,Williams,19.0,20.0,0.0,Retired
11,11,S PEREZ,PER,Red Bull Racing,20.0,10.0,0.0,Retired

## 3. Lap Data

Detailed lap-by-lap information for all drivers.

In [12]:
# Get all laps
laps = session.laps
print("Available columns in laps:")
print(laps.columns.tolist())
print(f"\nTotal number of laps: {len(laps)}")
print("\nSample lap data:")
laps.head()

Available columns in laps:
['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason', 'FastF1Generated', 'IsAccurate']

Total number of laps: 1035

Sample lap data:

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:58:27.597000,VER,1,0 days 00:01:39.510000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:39.931000,...,True,Red Bull Racing,0 days 00:56:47.817000,2024-12-08 13:03:35.034,12,11.0,False,,False,False
1,0 days 01:00:22.535000,VER,1,0 days 00:01:54.938000,2.0,1.0,NaT,NaT,0 days 00:00:18.209000,0 days 00:00:54.569000,...,True,Red Bull Racing,0 days 00:58:27.597000,2024-12-08 13:05:14.814,126,11.0,False,,False,False
2,0 days 01:02:00.586000,VER,1,0 days 00:01:38.051000,3.0,1.0,NaT,NaT,0 days 00:00:23.196000,0 days 00:00:41.997000,...,True,Red Bull Racing,0 days 01:00:22.535000,2024-12-08 13:07:09.752,671,10.0,False,,False,False
3,0 days 01:03:30.090000,VER,1,0 days 00:01:29.504000,4.0,1.0,NaT,NaT,0 days 00:00:18.166000,0 days 00:00:38.187000,...,True,Red Bull Racing,0 days 01:02:00.586000,2024-12-08 13:08:47.803,1,10.0,False,,False,True
4,0 days 01:04:59.903000,VER,1,0 days 00:01:29.813000,5.0,1.0,NaT,NaT,0 days 00:00:18.056000,0 days 00:00:37.945000,...,True,Red Bull Racing,0 days 01:03:30.090000,2024-12-08 13:10:17.307,1,10.0,False,,False,True

In [14]:
# Analyze lap times for a specific driver
driver_abbr = 'NOR'  # Change to any driver
driver_laps = laps.pick_driver(driver_abbr)
print(f"Sample laps data {driver_abbr}:")
driver_laps.head()

Sample laps data NOR:

/Users/martinakamodyova/VS Code/2025_f1_predictions/venv/lib/python3.12/site-packages/fastf1/core.py:3081: FutureWarning: pick_driver is deprecated and will be removed in a future release. Use pick_drivers instead.
  warnings.warn(("pick_driver is deprecated and will be removed"

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
632,0 days 00:58:19.229000,NOR,4,0 days 00:01:31.142000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:38.405000,...,True,McLaren,0 days 00:56:47.817000,2024-12-08 13:03:35.034,12,1.0,False,,False,False
633,0 days 01:00:07.578000,NOR,4,0 days 00:01:48.349000,2.0,1.0,NaT,NaT,0 days 00:00:18.242000,0 days 00:00:46.262000,...,True,McLaren,0 days 00:58:19.229000,2024-12-08 13:05:06.446,126,1.0,False,,False,False
634,0 days 01:01:50.891000,NOR,4,0 days 00:01:43.313000,3.0,1.0,NaT,NaT,0 days 00:00:25.352000,0 days 00:00:45.077000,...,True,McLaren,0 days 01:00:07.578000,2024-12-08 13:06:54.795,671,1.0,False,,False,False
635,0 days 01:03:19.901000,NOR,4,0 days 00:01:29.010000,4.0,1.0,NaT,NaT,0 days 00:00:18.280000,0 days 00:00:38.144000,...,True,McLaren,0 days 01:01:50.891000,2024-12-08 13:08:38.108,1,1.0,False,,False,True
636,0 days 01:04:49.005000,NOR,4,0 days 00:01:29.104000,5.0,1.0,NaT,NaT,0 days 00:00:18.253000,0 days 00:00:38.234000,...,True,McLaren,0 days 01:03:19.901000,2024-12-08 13:10:07.118,1,1.0,False,,False,True

In [9]:
# Analyze lap times for a specific driver
driver_abbr = 'VER'  # Change to any driver
driver_laps = laps.pick_driver(driver_abbr)
print(f"Laps for {driver_abbr}:")
driver_laps[['LapNumber', 'LapTime', 'Compound', 'TyreLife', 'Stint', 'TrackStatus']]

Laps for VER:

/Users/martinakamodyova/VS Code/2025_f1_predictions/venv/lib/python3.12/site-packages/fastf1/core.py:3081: FutureWarning: pick_driver is deprecated and will be removed in a future release. Use pick_drivers instead.
  warnings.warn(("pick_driver is deprecated and will be removed"

    LapNumber                LapTime Compound  TyreLife  Stint TrackStatus
0         1.0 0 days 00:01:39.510000   MEDIUM       1.0    1.0          12
1         2.0 0 days 00:01:54.938000   MEDIUM       2.0    1.0         126
2         3.0 0 days 00:01:38.051000   MEDIUM       3.0    1.0         671
3         4.0 0 days 00:01:29.504000   MEDIUM       4.0    1.0           1
4         5.0 0 days 00:01:29.813000   MEDIUM       5.0    1.0           1
5         6.0 0 days 00:01:29.412000   MEDIUM       6.0    1.0           1
6         7.0 0 days 00:01:29.885000   MEDIUM       7.0    1.0           1
7         8.0 0 days 00:01:29.824000   MEDIUM       8.0    1.0           1
8         9.0 0 days 00:01:29.445000   MEDIUM       9.0    1.0           1
9        10.0 0 days 00:01:30.449000   MEDIUM      10.0    1.0           1
10       11.0 0 days 00:01:30.395000   MEDIUM      11.0    1.0           1
11       12.0 0 days 00:01:30.164000   MEDIUM      12.0    1.0           1
12       13.0 0 days 00:01:30.178000   MEDIUM      13.0    1.0           1
13       14.0 0 days 00:01:30.128000   MEDIUM      14.0    1.0           1
14       15.0 0 days 00:01:29.876000   MEDIUM      15.0    1.0           1
15       16.0 0 days 00:01:30.047000   MEDIUM      16.0    1.0           1
16       17.0 0 days 00:01:29.909000   MEDIUM      17.0    1.0           1
17       18.0 0 days 00:01:29.826000   MEDIUM      18.0    1.0           1
18       19.0 0 days 00:01:30.076000   MEDIUM      19.0    1.0           1
19       20.0 0 days 00:01:30.004000   MEDIUM      20.0    1.0           1
20       21.0 0 days 00:01:29.695000   MEDIUM      21.0    1.0           1
21       22.0 0 days 00:01:29.889000   MEDIUM      22.0    1.0           1
22       23.0 0 days 00:01:29.939000   MEDIUM      23.0    1.0           1
23       24.0 0 days 00:01:29.750000   MEDIUM      24.0    1.0           1
24       25.0 0 days 00:01:29.852000   MEDIUM      25.0    1.0           1
25       26.0 0 days 00:01:30.268000   MEDIUM      26.0    1.0           1
26       27.0 0 days 00:01:29.897000   MEDIUM      27.0    1.0           1
27       28.0 0 days 00:01:30.274000   MEDIUM      28.0    1.0           1
28       29.0 0 days 00:01:31.857000   MEDIUM      29.0    1.0           1
29       30.0 0 days 00:01:59.495000     HARD       1.0    2.0          12
30       31.0 0 days 00:01:28.088000     HARD       2.0    2.0           1
31       32.0 0 days 00:01:28.528000     HARD       3.0    2.0           1
32       33.0 0 days 00:01:28.333000     HARD       4.0    2.0           1
33       34.0 0 days 00:01:28.409000     HARD       5.0    2.0           1
34       35.0 0 days 00:01:29.111000     HARD       6.0    2.0           1
35       36.0 0 days 00:01:28.557000     HARD       7.0    2.0           1
36       37.0 0 days 00:01:28.413000     HARD       8.0    2.0           1
37       38.0 0 days 00:01:28.360000     HARD       9.0    2.0           1
38       39.0 0 days 00:01:28.296000     HARD      10.0    2.0           1
39       40.0 0 days 00:01:28.345000     HARD      11.0    2.0           1
40       41.0 0 days 00:01:28.439000     HARD      12.0    2.0           1
41       42.0 0 days 00:01:28.113000     HARD      13.0    2.0           1
42       43.0 0 days 00:01:28.089000     HARD      14.0    2.0           1
43       44.0 0 days 00:01:28.501000     HARD      15.0    2.0           1
44       45.0 0 days 00:01:28.067000     HARD      16.0    2.0           1
45       46.0 0 days 00:01:28.231000     HARD      17.0    2.0           1
46       47.0 0 days 00:01:28.304000     HARD      18.0    2.0           1
47       48.0 0 days 00:01:27.893000     HARD      19.0    2.0           1
48       49.0 0 days 00:01:27.927000     HARD      20.0    2.0           1
49       50.0 0 days 00:01:27.961000     HARD      21.0    2.0           1
50       51.0 0 days 00:01:27.820000     HARD      22.0    2.0           1
51       52.0 0 days 00:01:28.047000     HARD      23.0    2.0           1
52       53.0 0 days 00:01:28.064000     HARD      24.0    2.0           1
53       54.0 0 days 00:01:28.352000     HARD      25.0    2.0           1
54       55.0 0 days 00:01:27.821000     HARD      26.0    2.0           1
55       56.0 0 days 00:01:27.765000     HARD      27.0    2.0           1
56       57.0 0 days 00:01:28.174000     HARD      28.0    2.0          12
57       58.0 0 days 00:01:28.780000     HARD      29.0    2.0           1

## 4. Telemetry Data

Detailed telemetry for specific laps (speed, throttle, brake, etc.).

In [15]:
# Get telemetry for a specific lap
fastest_lap = driver_laps.pick_fastest()
telemetry = fastest_lap.get_telemetry()

print("Available telemetry columns:")
print(telemetry.columns.tolist())
print("\nSample telemetry data:")
telemetry.head()

Available telemetry columns:
['Date', 'SessionTime', 'DriverAhead', 'DistanceToDriverAhead', 'Time', 'RPM', 'Speed', 'nGear', 'Throttle', 'Brake', 'DRS', 'Source', 'Distance', 'RelativeDistance', 'Status', 'X', 'Y', 'Z']

Sample telemetry data:

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z
2,2024-12-08 14:19:52.381,0 days 02:13:05.164000,,NaN,0 days 00:00:00,11168.293253,227.684210,5,99.759399,False,0,interpolation,0.072617,0.000014,OnTrack,620.177623,2086.846368,-239.000942
3,2024-12-08 14:19:52.456,0 days 02:13:05.239000,,NaN,0 days 00:00:00.075000,11072.428525,229.000001,5,99.571428,False,0,pos,4.887649,0.000937,OnTrack,694.000000,2096.000000,-239.000000
4,2024-12-08 14:19:52.684,0 days 02:13:05.467000,,NaN,0 days 00:00:00.303000,10781.000000,233.000000,6,99.000000,False,0,car,19.797500,0.003796,OnTrack,872.499313,2116.638618,-238.990602
5,2024-12-08 14:19:52.917,0 days 02:13:05.700000,,NaN,0 days 00:00:00.536000,11055.422147,239.472220,6,99.647222,False,0,pos,35.449972,0.006798,OnTrack,997.000000,2130.000000,-239.000000
6,2024-12-08 14:19:53.044,0 days 02:13:05.827000,,NaN,0 days 00:00:00.663000,11205.000000,243.000000,6,100.000000,False,0,car,44.097500,0.008456,OnTrack,1046.241468,2135.532509,-239.026192

## 5. Weather Data

Track and weather conditions during the session.

In [16]:
# Get weather data
weather = session.weather_data
print("Available weather columns:")
print(weather.columns.tolist())
print("\nWeather data summary:")
weather.describe()

Available weather columns:
['Time', 'AirTemp', 'Humidity', 'Pressure', 'Rainfall', 'TrackTemp', 'WindDirection', 'WindSpeed']

Weather data summary:

,Time,AirTemp,Humidity,Pressure,TrackTemp,WindDirection,WindSpeed
count,148,148.000000,148.000000,148.000000,148.000000,148.000000,148.000000
mean,0 days 01:14:27.206128378,26.768243,51.445946,1017.426351,31.805405,137.033784,1.900676
std,0 days 00:42:52.277080449,0.578767,5.678799,0.321002,1.984456,79.800808,0.642116
min,0 days 00:00:56.823000,25.800000,42.000000,1016.900000,29.100000,0.000000,0.600000
25%,0 days 00:37:42.035000,26.300000,46.000000,1017.100000,30.300000,105.750000,1.400000
50%,0 days 01:14:27.187500,26.800000,51.000000,1017.400000,31.300000,111.500000,1.800000
75%,0 days 01:51:12.344000,27.225000,57.250000,1017.700000,32.800000,126.750000,2.300000
max,0 days 02:27:57.568000,27.800000,60.000000,1018.000000,37.200000,324.000000,3.600000

## 6. Event Schedule

Get information about the season calendar.

In [17]:
# Get 2024 season schedule
schedule = fastf1.get_event_schedule(2024)
print("Available schedule columns:")
print(schedule.columns.tolist())
print("\n2024 Season Events:")
schedule[['RoundNumber', 'EventName', 'EventDate', 'Country', 'Location']]

Available schedule columns:
['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']

2024 Season Events:

,RoundNumber,EventName,EventDate,Country,Location
0,0,Pre-Season Testing,2024-02-23,Bahrain,Sakhir
1,1,Bahrain Grand Prix,2024-03-02,Bahrain,Sakhir
2,2,Saudi Arabian Grand Prix,2024-03-09,Saudi Arabia,Jeddah
3,3,Australian Grand Prix,2024-03-24,Australia,Melbourne
4,4,Japanese Grand Prix,2024-04-07,Japan,Suzuka
5,5,Chinese Grand Prix,2024-04-21,China,Shanghai
6,6,Miami Grand Prix,2024-05-05,United States,Miami
7,7,Emilia Romagna Grand Prix,2024-05-19,Italy,Imola
8,8,Monaco Grand Prix,2024-05-26,Monaco,Monaco
9,9,Canadian Grand Prix,2024-06-09,Canada,Montréal
10,10,Spanish Grand Prix,2024-06-23,Spain,Barcelona
11,11,Austrian Grand Prix,2024-06-30,Austria,Spielberg
12,12,British Grand Prix,2024-07-07,United Kingdom,Silverstone
13,13,Hungarian Grand Prix,2024-07-21,Hungary,Budapest
14,14,Belgian Grand Prix,2024-07-28,Belgium,Spa-Francorchamps
15,15,Dutch Grand Prix,2024-08-25,Netherlands,Zandvoort
16,16,Italian Grand Prix,2024-09-01,Italy,Monza
17,17,Azerbaijan Grand Prix,2024-09-15,Azerbaijan,Baku
18,18,Singapore Grand Prix,2024-09-22,Singapore,Marina Bay
19,19,United States Grand Prix,2024-10-20,United States,Austin
20,20,Mexico City Grand Prix,2024-10-27,Mexico,Mexico City
21,21,São Paulo Grand Prix,2024-11-03,Brazil,São Paulo
22,22,Las Vegas Grand Prix,2024-11-23,United States,Las Vegas
23,23,Qatar Grand Prix,2024-12-01,Qatar,Lusail
24,24,Abu Dhabi Grand Prix,2024-12-08,United Arab Emirates,Yas Island

In [22]:
# Get 2025 season schedule
schedule = fastf1.get_event_schedule(2025)
print("Available schedule columns:")
print(schedule.columns.tolist())
print("\n2025 Season Events:")
schedule[['RoundNumber', 'EventName', 'EventDate', 'Country', 'Location']]

Available schedule columns:
['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']

2025 Season Events:

,RoundNumber,EventName,EventDate,Country,Location
0,0,Pre-Season Testing,2025-02-28,Bahrain,Sakhir
1,1,Australian Grand Prix,2025-03-16,Australia,Melbourne
2,2,Chinese Grand Prix,2025-03-23,China,Shanghai
3,3,Japanese Grand Prix,2025-04-06,Japan,Suzuka
4,4,Bahrain Grand Prix,2025-04-13,Bahrain,Sakhir
5,5,Saudi Arabian Grand Prix,2025-04-20,Saudi Arabia,Jeddah
6,6,Miami Grand Prix,2025-05-04,United States,Miami Gardens
7,7,Emilia Romagna Grand Prix,2025-05-18,Italy,Imola
8,8,Monaco Grand Prix,2025-05-25,Monaco,Monaco
9,9,Spanish Grand Prix,2025-06-01,Spain,Barcelona
10,10,Canadian Grand Prix,2025-06-15,Canada,Montréal
11,11,Austrian Grand Prix,2025-06-29,Austria,Spielberg
12,12,British Grand Prix,2025-07-06,United Kingdom,Silverstone
13,13,Belgian Grand Prix,2025-07-27,Belgium,Spa-Francorchamps
14,14,Hungarian Grand Prix,2025-08-03,Hungary,Budapest
15,15,Dutch Grand Prix,2025-08-31,Netherlands,Zandvoort
16,16,Italian Grand Prix,2025-09-07,Italy,Monza
17,17,Azerbaijan Grand Prix,2025-09-21,Azerbaijan,Baku
18,18,Singapore Grand Prix,2025-10-05,Singapore,Marina Bay
19,19,United States Grand Prix,2025-10-19,United States,Austin
20,20,Mexico City Grand Prix,2025-10-26,Mexico,Mexico City
21,21,São Paulo Grand Prix,2025-11-09,Brazil,São Paulo
22,22,Las Vegas Grand Prix,2025-11-22,United States,Las Vegas
23,23,Qatar Grand Prix,2025-11-30,Qatar,Lusail
24,24,Abu Dhabi Grand Prix,2025-12-07,United Arab Emirates,Yas Island

In [23]:
# Get 2026 season schedule
schedule = fastf1.get_event_schedule(2026)
print("Available schedule columns:")
print(schedule.columns.tolist())
print("\n2026 Season Events:")
schedule[['RoundNumber', 'EventName', 'EventDate', 'Country', 'Location']]

logger      WARNING 	Failed to load schedule from FastF1 backend!
req            INFO 	No cached data found for season_schedule. Loading data...
_api           INFO 	Fetching season schedule...
logger      WARNING 	Failed to load schedule from F1 API backend!

Available schedule columns:
['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']

2026 Season Events:

Empty DataFrame
Columns: [RoundNumber, EventName, EventDate, Country, Location]
Index: []

## 7. Practice and Qualifying Data

Explore practice and qualifying sessions for additional insights.

In [18]:
# Load qualifying session
quali = fastf1.get_session(2024, 'Abu Dhabi', 'Q')
quali.load()

# Get qualifying results
quali_results = quali.results
print("Qualifying Results:")
quali_results[['Abbreviation', 'TeamName', 'Q1', 'Q2', 'Q3', 'Position']]

core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '55', '27', '1', '10', '63', '14', '77', '11', '22', '30', '18', '16', '20', '23', '24', '44', '43', '61']

Qualifying Results:

,Abbreviation,TeamName,Q1,Q2,Q3,Position
4,NOR,McLaren,0 days 00:01:23.682000,0 days 00:01:23.098000,0 days 00:01:22.595000,1.0
81,PIA,McLaren,0 days 00:01:23.640000,0 days 00:01:23.199000,0 days 00:01:22.804000,2.0
55,SAI,Ferrari,0 days 00:01:23.487000,0 days 00:01:22.985000,0 days 00:01:22.824000,3.0
27,HUL,Haas F1 Team,0 days 00:01:23.722000,0 days 00:01:23.040000,0 days 00:01:22.886000,4.0
1,VER,Red Bull Racing,0 days 00:01:23.516000,0 days 00:01:22.998000,0 days 00:01:22.945000,5.0
10,GAS,Alpine,0 days 00:01:23.548000,0 days 00:01:23.086000,0 days 00:01:22.984000,6.0
63,RUS,Mercedes,0 days 00:01:23.678000,0 days 00:01:23.283000,0 days 00:01:23.132000,7.0
14,ALO,Aston Martin,0 days 00:01:23.794000,0 days 00:01:23.268000,0 days 00:01:23.196000,8.0
77,BOT,Kick Sauber,0 days 00:01:23.481000,0 days 00:01:23.341000,0 days 00:01:23.204000,9.0
11,PER,Red Bull Racing,0 days 00:01:23.559000,0 days 00:01:23.379000,0 days 00:01:23.264000,10.0
22,TSU,RB,0 days 00:01:23.735000,0 days 00:01:23.419000,NaT,11.0
30,LAW,RB,0 days 00:01:23.733000,0 days 00:01:23.472000,NaT,12.0
18,STR,Aston Martin,0 days 00:01:23.729000,0 days 00:01:23.784000,NaT,13.0
16,LEC,Ferrari,0 days 00:01:23.302000,0 days 00:01:23.833000,NaT,14.0
20,MAG,Haas F1 Team,0 days 00:01:23.632000,0 days 00:01:23.877000,NaT,15.0
23,ALB,Williams,0 days 00:01:23.821000,NaT,NaT,16.0
24,ZHO,Kick Sauber,0 days 00:01:23.880000,NaT,NaT,17.0
44,HAM,Mercedes,0 days 00:01:23.887000,NaT,NaT,18.0
43,COL,Williams,0 days 00:01:23.912000,NaT,NaT,19.0
61,DOO,Alpine,0 days 00:01:24.105000,NaT,NaT,20.0

## 8. Driver and Team Information

Access driver and team metadata.

In [24]:
# Get driver information from results
drivers = results[['DriverNumber', 'BroadcastName', 'Abbreviation', 'TeamName', 'TeamColor', 'HeadshotUrl']]
print("Driver Information:")
drivers

Driver Information:

,DriverNumber,BroadcastName,Abbreviation,TeamName,TeamColor,HeadshotUrl
4,4,L NORRIS,NOR,McLaren,FF8000,https://media.formula1.com/d_driver_fallback_i...
55,55,C SAINZ,SAI,Ferrari,E80020,https://media.formula1.com/d_driver_fallback_i...
16,16,C LECLERC,LEC,Ferrari,E80020,https://media.formula1.com/d_driver_fallback_i...
44,44,L HAMILTON,HAM,Mercedes,27F4D2,https://media.formula1.com/d_driver_fallback_i...
63,63,G RUSSELL,RUS,Mercedes,27F4D2,https://media.formula1.com/d_driver_fallback_i...
1,1,M VERSTAPPEN,VER,Red Bull Racing,3671C6,https://media.formula1.com/d_driver_fallback_i...
10,10,P GASLY,GAS,Alpine,0093cc,https://media.formula1.com/d_driver_fallback_i...
27,27,N HULKENBERG,HUL,Haas F1 Team,B6BABD,https://media.formula1.com/d_driver_fallback_i...
14,14,F ALONSO,ALO,Aston Martin,229971,https://media.formula1.com/d_driver_fallback_i...
81,81,O PIASTRI,PIA,McLaren,FF8000,https://media.formula1.com/d_driver_fallback_i...
23,23,A ALBON,ALB,Williams,64C4FF,https://media.formula1.com/d_driver_fallback_i...
22,22,Y TSUNODA,TSU,RB,6692FF,https://media.formula1.com/d_driver_fallback_i...
24,24,G ZHOU,ZHO,Kick Sauber,52e252,https://media.formula1.com/d_driver_fallback_i...
18,18,L STROLL,STR,Aston Martin,229971,https://media.formula1.com/d_driver_fallback_i...
61,61,J DOOHAN,DOO,Alpine,0093cc,None
20,20,K MAGNUSSEN,MAG,Haas F1 Team,B6BABD,https://media.formula1.com/d_driver_fallback_i...
30,30,L LAWSON,LAW,RB,6692FF,None
77,77,V BOTTAS,BOT,Kick Sauber,52e252,https://media.formula1.com/d_driver_fallback_i...
43,43,F COLAPINTO,COL,Williams,64C4FF,None
11,11,S PEREZ,PER,Red Bull Racing,3671C6,https://media.formula1.com/d_driver_fallback_i...

## 9. Key Statistics

Calculate some useful statistics for predictions.

In [25]:
# Average lap times per driver
avg_lap_times = laps.groupby('Driver')['LapTime'].mean().sort_values()
print("Average Lap Times (excluding outliers):")
# Filter out pit laps and slow laps
clean_laps = laps[laps['IsPersonalBest'] | (laps['LapTime'] < laps['LapTime'].quantile(0.75))]
avg_lap_times_clean = clean_laps.groupby('Driver')['LapTime'].mean().sort_values()
print(avg_lap_times_clean)

Average Lap Times (excluding outliers):
Driver
NOR   0 days 00:01:29.146709090
SAI   0 days 00:01:29.231363636
HAM   0 days 00:01:29.541313725
LEC   0 days 00:01:29.560870370
VER   0 days 00:01:29.649660377
RUS   0 days 00:01:29.719851851
PIA   0 days 00:01:29.777207547
ALO   0 days 00:01:29.955061224
ZHO   0 days 00:01:30.284260869
GAS      0 days 00:01:30.328480
HUL      0 days 00:01:30.358020
STR      0 days 00:01:30.364425
MAG   0 days 00:01:30.422117647
LAW   0 days 00:01:30.479812500
ALB   0 days 00:01:30.724452380
TSU   0 days 00:01:30.736323529
DOO   0 days 00:01:31.083241379
BOT   0 days 00:01:31.918941176
COL   0 days 00:01:32.375142857
Name: LapTime, dtype: timedelta64[ns]

In [26]:
# Tire compound usage
tire_usage = laps.groupby(['Driver', 'Compound']).size().unstack(fill_value=0)
print("Tire Compound Usage by Driver:")
tire_usage

Tire Compound Usage by Driver:

Compound  HARD  MEDIUM  SOFT
Driver
ALB         45      12     0
ALO         45      13     0
BOT         24       6     0
COL         23       3     0
DOO         35      22     0
GAS         44      14     0
HAM         34      24     0
HUL         45      13     0
LAW         33      23     0
LEC         38      20     0
MAG         18      12    27
NOR         32      26     0
PER          0       1     0
PIA         54       4     0
RUS         32      26     0
SAI         33      25     0
STR         46      11     0
TSU         35      22     0
VER         29      29     0
ZHO         45      12     0

## 10. Data for Multiple Races

Example of collecting data across multiple races for pattern analysis.

In [27]:
# Collect results from last 3 races
recent_events = ['Las Vegas', 'Qatar', 'Abu Dhabi']
all_results = []

for event_name in recent_events:
    try:
        race = fastf1.get_session(2024, event_name, 'R')
        race.load()
        results_df = race.results[['Abbreviation', 'TeamName', 'Position', 'GridPosition', 'Points']].copy()
        results_df['Event'] = event_name
        all_results.append(results_df)
    except Exception as e:
        print(f"Could not load {event_name}: {e}")

if all_results:
    combined_results = pd.concat(all_results, ignore_index=True)
    print("Combined Recent Results:")
    print(combined_results)

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Driver 63: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 44: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 55: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 16: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver  1: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver  4: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 81: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 30: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 77: Lap timing integrity check failed for 2 lap(s)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 63 completed the race distance 00:00.427000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '1', '4', '81', '27', '22', '11', '14', '20', '24', '43', '18', '30', '31', '77', '23', '10']
events      WARNING 	Correcting user input 'Qatar' to 'Qatar Grand Prix'
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver  2: Position data is incomplete!
_api        WARNING 	Driver  3: Position data is incomplete!
_api        WARNING 	Driver  5: Position data is incomplete!
_api        WARNING 	Driver  6: Position data is incomplete!
_api        WARNING 	Driver  7: Position data is incomplete!
_api        WARNING 	Driver  8: Position data is incomplete!
_api        WARNING 	Driver  9: Position data is incomplete!
_api        WARNING 	Driver 12: Position data is incomplete!
_api        WARNING 	Driver 15: Position data is incomplete!
_api        WARNING 	Driver 17: Position data is incomplete!
_api        WARNING 	Driver 19: Position data is incomplete!
_api        WARNING 	Driver 21: Position data is incomplete!
_api        WARNING 	Driver 25: Position data is incomplete!
_api        WARNING 	Driver 26: Position data is incomplete!
_api        WARNING 	Driver 28: Position data is incomplete!
_api        WARNING 	Driver 29: Position data is incomplete!
_api        WARNING 	Driver 30: Position data is incomplete!
_api        WARNING 	Driver 31: Position data is incomplete!
_api        WARNING 	Driver 43: Position data is incomplete!
_api        WARNING 	Driver 44: Position data is incomplete!
_api        WARNING 	Driver 55: Position data is incomplete!
_api        WARNING 	Driver 63: Position data is incomplete!
_api        WARNING 	Driver 77: Position data is incomplete!
_api        WARNING 	Driver 81: Position data is incomplete!
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '10', '55', '14', '24', '20', '4', '77', '44', '22', '30', '23', '27', '11', '18', '43', '31']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']

Combined Recent Results:
   Abbreviation         TeamName  Position  GridPosition  Points      Event
0           RUS         Mercedes       1.0           1.0    25.0  Las Vegas
1           HAM         Mercedes       2.0          10.0    18.0  Las Vegas
2           SAI          Ferrari       3.0           2.0    15.0  Las Vegas
3           LEC          Ferrari       4.0           4.0    12.0  Las Vegas
4           VER  Red Bull Racing       5.0           5.0    10.0  Las Vegas
5           NOR          McLaren       6.0           6.0     9.0  Las Vegas
6           PIA          McLaren       7.0           8.0     6.0  Las Vegas
7           HUL     Haas F1 Team       8.0           9.0     4.0  Las Vegas
8           TSU               RB       9.0           7.0     2.0  Las Vegas
9           PER  Red Bull Racing      10.0          15.0     1.0  Las Vegas
10          ALO     Aston Martin      11.0          16.0     0.0  Las Vegas
11          MAG     Haas F1 Team      12.0          12.0     0.0  Las Vegas
12          ZHO      Kick Sauber      13.0          13.0     0.0  Las Vegas
13          COL         Williams      14.0          20.0     0.0  Las Vegas
14          STR     Aston Martin      15.0          18.0     0.0  Las Vegas
15          LAW               RB      16.0          14.0     0.0  Las Vegas
16          OCO           Alpine      17.0          11.0     0.0  Las Vegas
17          BOT      Kick Sauber      18.0          19.0     0.0  Las Vegas
18          ALB         Williams      19.0          17.0     0.0  Las Vegas
19          GAS           Alpine      20.0           3.0     0.0  Las Vegas
20          VER  Red Bull Racing       1.0           2.0    25.0      Qatar
21          LEC          Ferrari       2.0           5.0    18.0      Qatar
22          PIA          McLaren       3.0           4.0    15.0      Qatar
23          RUS         Mercedes       4.0           1.0    12.0      Qatar
24          GAS           Alpine       5.0          11.0    10.0      Qatar
25          SAI          Ferrari       6.0           7.0     8.0      Qatar
26          ALO     Aston Martin       7.0           8.0     6.0      Qatar
27          ZHO      Kick Sauber       8.0          12.0     4.0      Qatar
28          MAG     Haas F1 Team       9.0          10.0     2.0      Qatar
29          NOR          McLaren      10.0           3.0     2.0      Qatar
30          BOT      Kick Sauber      11.0          13.0     0.0      Qatar
31          HAM         Mercedes      12.0           6.0     0.0      Qatar
32          TSU               RB      13.0          14.0     0.0      Qatar
33          LAW               RB      14.0          17.0     0.0      Qatar
34          ALB         Williams      15.0          16.0     0.0      Qatar
35          HUL     Haas F1 Team      16.0          18.0     0.0      Qatar
36          PER  Red Bull Racing      17.0           9.0     0.0      Qatar
37          STR     Aston Martin      18.0          15.0     0.0      Qatar
38          COL         Williams      19.0          19.0     0.0      Qatar
39          OCO           Alpine      20.0          20.0     0.0      Qatar
40          NOR          McLaren       1.0           1.0    25.0  Abu Dhabi
41          SAI          Ferrari       2.0           3.0    18.0  Abu Dhabi
42          LEC          Ferrari       3.0          19.0    15.0  Abu Dhabi
43          HAM         Mercedes       4.0          16.0    12.0  Abu Dhabi
44          RUS         Mercedes       5.0           6.0    10.0  Abu Dhabi
45          VER  Red Bull Racing       6.0           4.0     8.0  Abu Dhabi
46          GAS           Alpine       7.0           5.0     6.0  Abu Dhabi
47          HUL     Haas F1 Team       8.0           7.0     4.0  Abu Dhabi
48          ALO     Aston Martin       9.0           8.0     2.0  Abu Dhabi
49          PIA          McLaren      10.0           2.0     1.0  Abu Dhabi
50          ALB         Williams      11.0          18.0     0.0  Abu Dhabi
51          TSU               RB      12.0          11.0     0.0  Abu Dhabi
52          ZHO      Kick Sauber      13.0          15.0     0.0  Abu Dhabi
53          STR     Aston Martin      14.0          13.0     0.0  Abu Dhabi
54          DOO           Alpine      15.0          17.0     0.0  Abu Dhabi
55          MAG     Haas F1 Team      16.0          14.0     0.0  Abu Dhabi
56          LAW               RB      17.0          12.0     0.0  Abu Dhabi
57          BOT      Kick Sauber      18.0           9.0     0.0  Abu Dhabi
58          COL         Williams      19.0          20.0     0.0  Abu Dhabi
59          PER  Red Bull Racing      20.0          10.0     0.0  Abu Dhabi

## Summary

Key data available for predictions:
- **Results**: Final positions, grid positions, points, status
- **Laps**: Lap times, tire compounds, stint information, track status
- **Telemetry**: Speed, throttle, brake, gear, DRS (per lap)
- **Weather**: Track temp, air temp, humidity, rainfall, wind
- **Schedule**: Event information, dates, locations
- **Qualifying**: Q1/Q2/Q3 times and positions

This data can be used to build features for race predictions!